/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/OsoTed.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1.81, 0]}>
        <mesh geometry={nodes.Cilindro001.geometry} material={materials.OsoPiel} />
        <mesh geometry={nodes.Cilindro001_1.geometry} material={materials.Ojos} />
        <mesh geometry={nodes.Cilindro001_2.geometry} material={materials.Nariz} />
        <mesh geometry={nodes.Cilindro001_3.geometry} material={materials.OjosOso} />
      </group>
    </group>
  )
}

useGLTF.preload('/OsoTed.gltf')
