/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Paperclip.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.Material}
        position={[-19.35, 0, -0.36]}
        rotation={[0, 0.01, -Math.PI / 2]}
        scale={[-0.06, 20.39, -0.06]}
      />
    </group>
  )
}

useGLTF.preload('/Paperclip.gltf')
