/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./../Assets/Pencil.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[9.76, 0, 0]} rotation={[1.28, -0.73, -0.04]} scale={[1, 1, 1.12]}>
        <mesh geometry={nodes.Цилиндр001.geometry} material={materials['pencil paint']} />
        <mesh geometry={nodes.Цилиндр001_1.geometry} material={materials['Материал.003']} />
        <mesh geometry={nodes.Цилиндр001_2.geometry} material={materials['Материал.004']} />
        <mesh geometry={nodes.Цилиндр001_3.geometry} material={materials['Материал.Carbon']} />
        <group position={[0, 10.32, 0]} scale={[0.54, 0.93, 0.48]}>
          <mesh geometry={nodes.Цилиндр_1.geometry} material={materials.Gold} />
          <mesh geometry={nodes.Цилиндр_2.geometry} material={materials['Материал.007']} />
          <mesh geometry={nodes.Цилиндр_3.geometry} material={materials.Eraser} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Pencil.gltf')
