/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tazita.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.tea_mug.geometry}
        material={materials.teamug}
        position={[0, 1.19, 0]}
        rotation={[0, -0.63, 0]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[0.29, -1.81, 4.08]}
        scale={[-967.81, -229.77, -1087.09]}
      />
    </group>
  )
}

useGLTF.preload('/tazita.gltf')
